
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fufkgbehjidcoytcrdlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1ZmtnYmVoamlkY295dGNyZGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTU0NTksImV4cCI6MjA1OTg3MTQ1OX0.dds_sB2HNUK6gSaFZCk_ghl5OtOsMCseXIGyvTGWqnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      persistSession: true,
      storage: localStorage,
      autoRefreshToken: true,
      detectSessionInUrl: true, // Critical for OAuth redirects
      flowType: 'implicit' // Use implicit flow for browser-based auth
    }
  }
);
